# Generated by Django 3.0.5 on 2020-09-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_undertertiarycategory'),
        ('product', '0002_auto_20200925_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_under_tertiary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.UnderTertiaryCategory'),
        ),
    ]
