# Generated by Django 3.0.5 on 2020-08-08 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_login', '0002_auto_20200722_1147'),
        ('attribute', '0003_nextdaydelivary'),
        ('category', '0001_initial'),
        ('seller', '0003_auto_20200808_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_custom_id', models.CharField(max_length=200, unique=True)),
                ('prod_title', models.CharField(max_length=250)),
                ('prod_desc', models.CharField(max_length=300)),
                ('same_day_delivery', models.BooleanField(default=False)),
                ('same_day_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('next_day_delivery', models.BooleanField(default=False)),
                ('next_day_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('customize_day_delivery', models.BooleanField(default=False)),
                ('customize_day_delivery_day', models.IntegerField(blank=True)),
                ('customize_day_delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('weekly_dreals', models.BooleanField(default=False)),
                ('top_offer', models.BooleanField(default=False)),
                ('product_return', models.BooleanField(default=False)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('youtube_link', models.URLField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_login.zaptayAdmin')),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.MainCategory')),
                ('prod_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.Colour')),
                ('prod_made_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.Source')),
                ('prod_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.Size')),
                ('prod_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.SubCategory')),
                ('prod_tertiary_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.TertiaryCategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
