# Generated by Django 3.0.5 on 2020-08-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20200821_1303'),
        ('product', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_tertiary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.TertiaryCategory'),
        ),
    ]
