# Generated by Django 3.0.5 on 2020-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_custom_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
