# Generated by Django 3.0.5 on 2020-09-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_brand'),
        ('product', '0005_auto_20200823_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attribute.Brand'),
        ),
    ]
