# Generated by Django 3.0.5 on 2020-08-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
