# Generated by Django 3.0.5 on 2020-09-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_usercartlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='ph_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
