# Generated by Django 3.0.5 on 2020-07-27 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0002_auto_20200722_1147'),
        ('category', '0001_initial'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TertiaryCategory',
            fields=[
                ('ter_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('ter_category_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_login.zaptayAdmin')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.MainCategory')),
            ],
            options={
                'db_table': 'tertiary_category',
            },
        ),
    ]
