# Generated by Django 3.0.5 on 2020-07-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_tertiarycategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tertiarycategory',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.SubCategory'),
        ),
    ]
