# Generated by Django 3.0.5 on 2020-08-04 09:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0002_auto_20200722_1147'),
        ('attribute', '0002_samedaydelivary'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextDayDelivary',
            fields=[
                ('next_day_pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('is_active', models.BooleanField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_login.zaptayAdmin')),
            ],
            options={
                'db_table': 'next_day_delivary_pincode',
            },
        ),
    ]
