# Generated by Django 3.0.5 on 2020-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_nextdaydelivary'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_image',
            field=models.ImageField(default='', upload_to='sub_category/images'),
        ),
        migrations.AddField(
            model_name='tertiarycategory',
            name='tertiary_category_image',
            field=models.ImageField(default='', upload_to='tertiary_category/images'),
        ),
    ]
