# Generated by Django 3.0.5 on 2020-09-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20200821_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_category_seo_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
