# Generated by Django 3.0.5 on 2020-09-25 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0002_auto_20200722_1147'),
        ('attribute', '0006_tertiarycategory_ter_category_seo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=1)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_login.zaptayAdmin')),
            ],
            options={
                'db_table': 'brands',
            },
        ),
    ]
