# Generated by Django 3.0.5 on 2020-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zaptayadmin',
            old_name='emai_id',
            new_name='email_id',
        ),
    ]
