# Generated by Django 3.0.5 on 2020-08-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_login', '0002_auto_20200722_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_image', models.ImageField(blank=True, default='', null=True, upload_to='banner/men_fashion/images')),
                ('banner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('banner_link', models.URLField(blank=True, null=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_login.zaptayAdmin')),
            ],
            options={
                'db_table': 'banners',
            },
        ),
    ]
