# Generated by Django 3.0.5 on 2020-09-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_name_custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
