# Generated by Django 3.0.5 on 2020-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_custom_id', models.CharField(max_length=100, unique=True)),
                ('user_f_name', models.CharField(max_length=100)),
                ('user_l_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=150)),
                ('passwd', models.CharField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
