# Generated by Django 3.0.5 on 2020-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_custom_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
